from time import sleep
user_name = input('What is your name? ')
sleep(1)
adjective1 = input('Enter first adjective: ')
sleep(1)
adjective2 = input('Enter second adjective: ')
sleep(1)
adjective3 = input('Enter third adjective: ')
sleep(1)
verb1 = input('Enter first verb: ')
sleep(1)
verb2 = input('Enter second verb: ')
sleep(1)
verb3 = input('Enter third verb: ')
sleep(1)
noun1 = input('Enter first noun: ')
sleep(1)
noun2 = input('Enter second noun: ')
sleep(1)
noun3 = input('Enter third noun: ')
noun4 = input('Enter fourth noun: ')
animal = input('Enter an animal: ')
food = input('Enter a food: ')
fruit = input('Enter a fruit: ')
number = input('Enter a number: ')
superhero =input('Enter a superhero: ')
country = input('Enter a country: ')
dessert = input('Enter a dessert: ')
year = input('Enter a year: ')


story = "This morning I woke up and felt %s because %s was going to finally %s over\nthe big %s %s. On the other side of the %s were many %ss protesting to keep %s in stores.\nThe crowd began to %s to the rhythm of the %s,\nwhich made all of the %ss very %s. %s tried to %s into the sewers and\nfound %s rats. Needing help, %s quickly called %s. %s appeared and saved %s by flying to %s and\ndropping %s into a puddle of %s. %s then fell asleep and woke up in the year %s, in a world\nwhere %ss ruled the world."
print (story % (adjective1, user_name, verb1, adjective2, noun1, noun2, animal, food, verb2, noun3, fruit, adjective3, user_name, verb3, number, user_name, superhero, superhero, user_name, country, user_name, dessert, user_name, year, noun4))

